server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/saga_sale?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: example
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: false
      database-platform: org.hibernate.dialect.MySQL8Dialect
      open-in-view: false
      generate-ddl: false
      properties:
        hibernate.format_sql: false
  flyway:
    enabled: true
    group: true
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    schemas: saga_sale
    locations: classpath:db/migration